### ISSUE TITLE
preferences is a pretty bad name for a key

### ISSUE THREAD

**Issue by hseeberger** [daniel-trinh/sbt-scalariform#13]
Kudos for changing this to an auto plugin. Yet now all members of `autoImport` are available without a prefix which is particularly odd for `preferences`. Maybe rename that to `scalariformPreferences`?

**Comment by daniel-trinh** [comment]
fixed in #14 (release 1.5.1)

**Comment by hseeberger** [comment]
Thanks for the quick fix!
