### ISSUE TITLE
defaultScalariformSettings includes compile hooks when it shouldn't

### ISSUE THREAD

**Issue by dispalt** [daniel-trinh/sbt-scalariform#15]
Somewhere between `1.4.0` and `1.5.0` the `defaultScalariformSettings` settings trick no longer avoids compiling automatically.  I looked at the code and can't understand why its working that way, but maybe it has something to do with autoPlugins.

**Comment by daniel-trinh** [comment]
Can you post a sample .sbt / build.scala config? I think this might be due to scalariformSettings being used automatically instead of defaultScalariformSettings

**Comment by normenmueller** [comment]
Same with v1.6.0.

Although using `SbtScalariform.defaultScalariformSettings` is formats during compilation.

**Comment by normenmueller** [comment]
@daniel-trinh Please have a look at https://github.com/daniel-trinh/sbt-scalariform/pull/26

**Comment by daniel-trinh** [comment]
I'm not actually able to reproduce what's described in #15, so far, adding defaultScalariformSettings seems to work fine for disabling auto formatting (example below).

``` scala
  val sbtScalariform: Project = Project(
    "sbt-scalariform",
    file("."),
    settings =  SbtScalariform.defaultScalariformSettings ++ Seq(
   ...
```

If this is happening for someone, a reproducible project with this happening would help.

**Comment by normenmueller** [comment]
@daniel-trinh Please have a look at https://github.com/normenmueller/sbt-scalariform-issue-15.

In `src/main/scala/Main.scala`, I modify

``` scala
/** This
  * is
  * a multiline
  * comment
  */
object Main extends App {
  println("Hello")
}
```

to

``` scala
/** This
  * is
* a multiline
  * comment
  */
object Main extends App {
  println("Hello")
}
```

and run `compile` in Sbt which yields the first code snippet.

**Comment by normenmueller** [comment]
@daniel-trinh Any news?

**Comment by daniel-trinh** [comment]
@normenmueller I confirmed that the bug exists in your project example. I haven't gotten to figuring out what the cause is yet, though. It might have to do something with the order of settings being included to the project.

**Comment by normenmueller** [comment]
What about this `override lazy val projectSettings = scalariformSettings`?

**Comment by stewSquared** [comment]
@daniel-trinh You mentioned being unable to reproduce the bug. Do you have a project for which the bug doesn't exist?

**Comment by koertkuipers** [comment]
instead of the complex importing of different settings how about a simple key that i can put in my config to disable the auto formatting?

**Comment by jrlemieux** [comment]
I can confirm that this bug still exists. It actually makes the formater unusable from within SBT as the editor keeps on asking to auto-reload the edited file (when a sbt ~compile is active). I will rather investigate how to run the formater stand-alone outside of sbt.

**Comment by jrlemieux** [comment]
It is surprising that this bug still exists after one year.
