### ISSUE TITLE
chained methods not properly intendet

### ISSUE THREAD

**Issue by cvogt** [daniel-trinh/sbt-scalariform#19]
expected

``` scala
l.filter(
  r contains _
).filter(
  r contains _
).toList
```

actual

``` scala
l.filter(
  r contains _
).filter(
    r contains _
  ).toList
```

probably related to #18

**Comment by jawshooah** [comment]
Just FYI, this and #18 belong on the main [scalariform repo](https://github.com/daniel-trinh/scalariform). This repo is specifically for the SBT plugin.

**Comment by cvogt** [comment]
thx. closed in favor of https://github.com/daniel-trinh/scalariform/issues/84
