### ISSUE TITLE
do not automatically reformat everything

### ISSUE THREAD

**Issue by fommil** [daniel-trinh/sbt-scalariform#24]
**THIS TICKET HAS MOVED HOME** https://github.com/sbt/sbt-scalariform/issues/30

---

I just upgraded our version of sbt-scalariform in ensime-sbt and now all of our users are having their code automatically reformatted!!

This should be opt-in, not forced. Please issue a quick fix. Looks like the problem was introduced here https://github.com/daniel-trinh/sbt-scalariform/blob/master/src/main/scala/com/typesafe/sbt/SbtScalariform.scala#L59 where `projectSettings` is overridden. Just removing this one line should fix it.

**Comment by daniel-trinh** [comment]
So what's going on here? sbt-scalariform is intended to format just the ensime-sbt codebase, but it ends up formatting anyone that depends on the ensime-sbt library?

`override lazy val projectSettings = scalariformSettings` was added I believe to get autoplugin behavior working so that anyone using sbt-scalariform will be able to have their code formatted without defining explicit settings on their projects, but if it's also automatically formatting code on projects that are built with the plugin internally, then that is unintended behavior.

**Comment by fommil** [comment]
I don't believe this auto format thing is good, even for straight scalariform users. It's always been opt-in per project and now it's forced everywhere.

**Comment by daniel-trinh** [comment]
It's not intended to be "forced", if there's no way to opt out of the auto formatting with a setting change then that is unintended. What is intended is simplifying the necessary steps to getting code auto formatted on compilation -- that is not having to include scalariform preferences in the build settings. 

This addition came out of a request of a couple other users for auto plugin behavior. I imagine there are going to be people in both camps who want the old behavior as well.

I still don't understand what the exact problem is with the current situation, if there is a way to not have it auto format with a setting, is that not enough?

**Comment by fommil** [comment]
I've been reading up on plugins. the problem is with `override val trigger = allRequirements`.

This should be omitted, meaning that users should opt-in to use scalariform.

**Comment by fommil** [comment]
i.e. if someone wants to use the autoplugin, they need to `.enablePlugins(SbtScalariform)`.

With the current release, if sbt-scalariform is available, anywhere on the user's sbt classpath, it will be used. I think we want `noTrigger` http://www.scala-sbt.org/0.13/api/index.html#sbt.AutoPlugin

**Comment by fommil** [comment]
@daniel-trinh I found the cause to this, can you please issue a release with that trigger line removed please?

**Comment by daniel-trinh** [comment]
ACK, a bit busy this week but it's on my radar

**Comment by fommil** [comment]
cool, thanks!
