### ISSUE TITLE
Release new version using 0.1.6 scalariform

### ISSUE THREAD

**Issue by daniel-trinh** [daniel-trinh/sbt-scalariform#4]

**Comment by fommil** [comment]
you've not rebased your fork with the upstream version, so things like `scalariformSettingsWithIt` are missing.

I think it would be a good idea to simply coordinate with https://github.com/sbt/sbt-scalariform/issues/20 and turn this fork into a pom-only project.

**Comment by daniel-trinh** [comment]
0.1.5 has been released and should be rebased with the upstream version (along with a few other additions)
