### ISSUE TITLE
AutoPlugin

### ISSUE THREAD

**Issue by giabao** [daniel-trinh/sbt-scalariform#9]
I think sbt-scalariform should be sbt AutoPlugin

**Comment by ghost** [comment]
+1. Please make this an autoplugin

**Comment by daniel-trinh** [comment]
#10 Attempts to implement this as an autoplugin, although it doesn't seem like auto formatting works on compilation. I don't suppose anyone reading this is an sbt expert and wants to take a look?

**Comment by daniel-trinh** [comment]
this is complete as part of #10
